import type { FeedSource } from '../types'

export const DEFAULT_FEED_SOURCES: FeedSource[] = [
  {
    id: 'hacker-news-frontpage',
    name: 'Hacker News Front Page',
    url: 'https://hnrss.org/frontpage',
    category: 'general',
    isActive: true,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'aws-status',
    name: 'AWS Service Health Dashboard',
    url: 'https://status.aws.amazon.com/rss/all.rss',
    category: 'outage',
    isActive: true,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'gcp-status',
    name: 'Google Cloud Service Health',
    url: 'https://status.cloud.google.com/feed.atom',
    category: 'outage',
    isActive: true,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'azure-status',
    name: 'Azure Service Status',
    url: 'https://status.azure.com/en-us/status/feed/',
    category: 'outage',
    isActive: true,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'bleepingcomputer',
    name: 'BleepingComputer',
    url: 'https://www.bleepingcomputer.com/feed/',
    category: 'security',
    isActive: true,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'krebs',
    name: 'Krebs on Security',
    url: 'https://krebsonsecurity.com/feed/',
    category: 'security',
    isActive: true,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'cisa-alerts',
    name: 'CISA Alerts',
    url: 'https://www.cisa.gov/news-events/cybersecurity-advisories/all.xml',
    category: 'vulnerability',
    isActive: true,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'techcrunch',
    name: 'TechCrunch',
    url: 'https://techcrunch.com/feed/',
    category: 'release',
    isActive: true,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'ars-technica',
    name: 'Ars Technica',
    url: 'https://feeds.arstechnica.com/arstechnica/index',
    category: 'general',
    isActive: true,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'the-register-security',
    name: 'The Register - Security',
    url: 'https://www.theregister.com/security/headlines.atom',
    category: 'security',
    isActive: true,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'github-blog',
    name: 'GitHub Blog',
    url: 'https://github.blog/feed/',
    category: 'release',
    isActive: true,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'nist-nvd',
    name: 'NIST NVD News',
    url: 'https://nvd.nist.gov/feeds/xml/cve/misc/nvd-rss.xml',
    category: 'vulnerability',
    isActive: true,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'cloudflare-status',
    name: 'Cloudflare Status',
    url: 'https://www.cloudflarestatus.com/history.atom',
    category: 'outage',
    isActive: true,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'datadog-status',
    name: 'Datadog Status',
    url: 'https://status.datadoghq.com/history.atom',
    category: 'outage',
    isActive: true,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'reddit-netsec',
    name: 'Reddit /r/netsec',
    url: 'https://www.reddit.com/r/netsec/.rss',
    category: 'security',
    isActive: false,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'cso-online',
    name: 'CSO Online',
    url: 'https://www.csoonline.com/feed/',
    category: 'security',
    isActive: false,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'zdnet-security',
    name: 'ZDNet Security',
    url: 'https://www.zdnet.com/topic/security/rss.xml',
    category: 'security',
    isActive: false,
    lastPolled: null,
    lastError: null,
  },
  {
    id: 'therecord-media',
    name: 'The Record by Recorded Future',
    url: 'https://therecord.media/feed',
    category: 'security',
    isActive: false,
    lastPolled: null,
    lastError: null,
  },
]
