import type { Vendor } from '../types'

export const VENDOR_REGISTRY: Vendor[] = [
  {
    id: 'aws',
    name: 'Amazon Web Services',
    packages: ['@aws-sdk/*', 'aws-sdk', 'aws-amplify'],
    keywords: ['AWS', 'S3', 'EC2', 'Lambda', 'DynamoDB', 'CloudFront', 'IAM', 'RDS'],
    regions: ['us-east-1', 'us-west-2', 'eu-west-1', 'ap-southeast-1'],
    aliases: ['amazon web services', 'amazon aws'],
  },
  {
    id: 'gcp',
    name: 'Google Cloud Platform',
    packages: ['@google-cloud/*', 'firebase-admin', 'firebase'],
    keywords: ['GCP', 'Google Cloud', 'Cloud Run', 'BigQuery', 'Cloud Storage', 'GKE'],
    regions: ['us-central1', 'europe-west1', 'asia-east1'],
    aliases: ['google cloud platform', 'google cloud'],
  },
  {
    id: 'azure',
    name: 'Microsoft Azure',
    packages: ['@azure/*', 'azure-storage'],
    keywords: ['Azure', 'Azure Functions', 'Blob Storage', 'AKS', 'Cosmos DB'],
    regions: ['eastus', 'westus2', 'westeurope', 'southeastasia'],
    aliases: ['microsoft azure'],
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    packages: ['cloudflare', 'wrangler', '@cloudflare/*'],
    keywords: ['Cloudflare', 'Workers', 'R2', 'KV', 'Durable Objects', 'Pages'],
    regions: ['global'],
    aliases: ['cf', 'cloudflare inc'],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    packages: ['stripe', '@stripe/stripe-js', '@stripe/react-stripe-js'],
    keywords: ['Stripe', 'PaymentIntent', 'Checkout', 'Radar', 'Connect'],
    regions: ['us', 'eu', 'apac'],
    aliases: ['stripe payments'],
  },
  {
    id: 'twilio',
    name: 'Twilio',
    packages: ['twilio', '@twilio/*'],
    keywords: ['Twilio', 'Programmable SMS', 'SendGrid', 'Voice API'],
    regions: ['us1', 'ie1', 'au1'],
    aliases: ['twilio inc'],
  },
  {
    id: 'firebase',
    name: 'Firebase',
    packages: ['firebase', 'firebase-admin', '@firebase/*'],
    keywords: ['Firebase', 'Firestore', 'Realtime Database', 'Firebase Auth', 'Cloud Messaging'],
    regions: ['us-central', 'europe-west', 'asia-south'],
    aliases: ['google firebase'],
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    packages: ['mongodb', 'mongoose'],
    keywords: ['MongoDB', 'Atlas', 'BSON', 'Replica Set', 'Sharding'],
    regions: ['us-east-1', 'eu-west-1', 'ap-southeast-2'],
    aliases: ['mongo', 'mongodb atlas'],
  },
  {
    id: 'redis',
    name: 'Redis',
    packages: ['redis', 'ioredis', '@redis/*'],
    keywords: ['Redis', 'Redis Cluster', 'Redis Sentinel', 'Cache'],
    regions: ['global'],
    aliases: ['redis labs', 'redis enterprise'],
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    packages: ['pg', 'postgres', 'postgresql-client'],
    keywords: ['PostgreSQL', 'Postgres', 'logical replication', 'WAL'],
    regions: ['global'],
    aliases: ['postgres', 'pgsql'],
  },
  {
    id: 'github',
    name: 'GitHub',
    packages: ['@octokit/*', 'octokit'],
    keywords: ['GitHub', 'GitHub Actions', 'Dependabot', 'GitHub API'],
    regions: ['global'],
    aliases: ['gh', 'github.com'],
  },
  {
    id: 'npm',
    name: 'npm',
    packages: ['npm', 'npm-registry-fetch'],
    keywords: ['npm', 'npm registry', 'npm package'],
    regions: ['global'],
    aliases: ['node package manager'],
  },
  {
    id: 'docker',
    name: 'Docker',
    packages: ['dockerode', '@docker/*'],
    keywords: ['Docker', 'Docker Hub', 'container image', 'Docker Engine'],
    regions: ['global'],
    aliases: ['docker inc'],
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    packages: ['@kubernetes/client-node', 'kubernetes-client'],
    keywords: ['Kubernetes', 'K8s', 'kubectl', 'Helm', 'Ingress'],
    regions: ['global'],
    aliases: ['k8s'],
  },
  {
    id: 'vercel',
    name: 'Vercel',
    packages: ['vercel', '@vercel/*'],
    keywords: ['Vercel', 'Edge Functions', 'Vercel KV', 'ISR'],
    regions: ['iad1', 'cdg1', 'hnd1'],
    aliases: ['vercel platform'],
  },
  {
    id: 'netlify',
    name: 'Netlify',
    packages: ['netlify', '@netlify/*'],
    keywords: ['Netlify', 'Netlify Functions', 'Netlify Edge'],
    regions: ['global'],
    aliases: ['netlify inc'],
  },
  {
    id: 'supabase',
    name: 'Supabase',
    packages: ['@supabase/supabase-js', '@supabase/*'],
    keywords: ['Supabase', 'PostgREST', 'Supabase Auth', 'Supabase Realtime'],
    regions: ['us-east-1', 'eu-central-1', 'ap-southeast-1'],
    aliases: ['supabase io'],
  },
  {
    id: 'auth0',
    name: 'Auth0',
    packages: ['auth0', '@auth0/*'],
    keywords: ['Auth0', 'Universal Login', 'OIDC', 'tenant'],
    regions: ['us', 'eu', 'au'],
    aliases: ['okta auth0'],
  },
  {
    id: 'sendgrid',
    name: 'SendGrid',
    packages: ['@sendgrid/mail', '@sendgrid/client'],
    keywords: ['SendGrid', 'Transactional Email', 'Email API'],
    regions: ['global'],
    aliases: ['twilio sendgrid'],
  },
  {
    id: 'datadog',
    name: 'Datadog',
    packages: ['datadog', 'dd-trace', '@datadog/*'],
    keywords: ['Datadog', 'APM', 'RUM', 'Logs', 'Synthetic Monitoring'],
    regions: ['us1', 'eu1', 'us3', 'us5'],
    aliases: ['ddog'],
  },
  {
    id: 'newrelic',
    name: 'New Relic',
    packages: ['newrelic', '@newrelic/*'],
    keywords: ['New Relic', 'NRQL', 'APM', 'Browser Monitoring'],
    regions: ['us', 'eu'],
    aliases: ['new relic'],
  },
  {
    id: 'sentry',
    name: 'Sentry',
    packages: ['@sentry/*', 'sentry'],
    keywords: ['Sentry', 'Error Tracking', 'Performance Monitoring', 'Replay'],
    regions: ['us', 'eu'],
    aliases: ['sentry io'],
  },
  {
    id: 'planetscale',
    name: 'PlanetScale',
    packages: ['@planetscale/database', 'planetscale-node'],
    keywords: ['PlanetScale', 'Vitess', 'branching database'],
    regions: ['us-east', 'us-west', 'eu-west'],
    aliases: ['planetscale db'],
  },
  {
    id: 'prisma',
    name: 'Prisma',
    packages: ['prisma', '@prisma/client'],
    keywords: ['Prisma', 'Prisma Client', 'Prisma Migrate'],
    regions: ['global'],
    aliases: ['prisma orm'],
  },
  {
    id: 'drizzle',
    name: 'Drizzle',
    packages: ['drizzle-orm', 'drizzle-kit'],
    keywords: ['Drizzle', 'Drizzle ORM', 'Drizzle Kit'],
    regions: ['global'],
    aliases: ['drizzle orm'],
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    packages: ['next'],
    keywords: ['Next.js', 'App Router', 'Pages Router', 'ISR', 'Server Components'],
    regions: ['global'],
    aliases: ['nextjs'],
  },
  {
    id: 'react',
    name: 'React',
    packages: ['react', 'react-dom'],
    keywords: ['React', 'React DOM', 'React Hooks', 'JSX'],
    regions: ['global'],
    aliases: ['reactjs'],
  },
  {
    id: 'vue',
    name: 'Vue',
    packages: ['vue', '@vue/*'],
    keywords: ['Vue', 'Vue Router', 'Pinia', 'Nuxt'],
    regions: ['global'],
    aliases: ['vuejs'],
  },
  {
    id: 'angular',
    name: 'Angular',
    packages: ['@angular/*'],
    keywords: ['Angular', 'Angular CLI', 'RxJS', 'Zone.js'],
    regions: ['global'],
    aliases: ['angularjs', 'ng'],
  },
]

export const VENDOR_BY_ID = new Map<string, Vendor>(
  VENDOR_REGISTRY.map((vendor) => [vendor.id, vendor]),
)
